package com.SeeShell.demo;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.jacob.activeX.ActiveXComponent;
import com.jacob.com.Variant;

import javax.swing.*;
import java.awt.*;

/**
 * SeeShell API Java Demo, V1.2, 2018/8/28
 * (c) a9t9 tech support
 * License: Free to use for SeeShell PRO users
 */

public class MainApp extends JFrame {
    private final StringBuilder logBuffer = new StringBuilder();
    public JPanel mainPanel;
    private JButton btnRunSeeShell;
    private JTextField scriptField;
    private JTextArea logsArea;

    private MainApp() {
        setTitle("SeeShell API - Java Demo V1.2");
        setContentPane(mainPanel);
        setResizable(false);
        pack();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        btnRunSeeShell.addActionListener(e -> {
            try {
                log("Starting SeeShell Browser");
                String myScript = scriptField.getText();
                ActiveXComponent SeeShell = new ActiveXComponent("SeeShell");

                //open the SeeShell Browser. With SeeShell.open(false) you can connect to an already open instance
                Variant result = SeeShell.invoke("open", new Variant(true));
                if (result.getInt() < 0) {
                    log("SeeShell Open Error: " + result + " Text: " + getLastError(SeeShell));
                }

                SeeShell.invoke("echo", new Variant("Hello from the Java app: " + myScript));
                log("Start Script " + myScript);

                result = SeeShell.invoke("play", new Variant(myScript));
                if (result.getInt() < 0) {
                    log("Script Replay Error: " + result + " Text: " + getLastError(SeeShell));
                } else {
                    log("Script completed - OK");
                }

                SeeShell.invoke("echo", new Variant("Done"));

                log("Closing SeeShell Browser ...");
                SeeShell.invoke("close");
            } catch (Exception ex) {
                log("An exception occurred " + ex.getMessage());
                ex.printStackTrace();
            }
        });
    }

    private String getLastError(ActiveXComponent SeeShell) {
        return SeeShell.invoke("getLastError").toString();
    }

    private void log(String message) {
        logBuffer.append(message).append("\n");
        logsArea.setText(logBuffer.toString());
        logsArea.update(logsArea.getGraphics()); // revalidate logs on form
    }

    public static void main(String[] args) {
        new MainApp().setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 3, new Insets(15, 15, 15, 15), -1, -1));
        mainPanel.setMinimumSize(new Dimension(500, 400));
        mainPanel.setPreferredSize(new Dimension(500, 400));
        btnRunSeeShell = new JButton();
        btnRunSeeShell.setActionCommand("");
        btnRunSeeShell.setText("Run SeeShell");
        mainPanel.add(btnRunSeeShell, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Script:");
        mainPanel.add(label1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scriptField = new JTextField();
        scriptField.setText("Demo-Automate-Forms");
        scriptField.setToolTipText("File name without extension. File must be present in '<Current User>\\Documents\\SeeShell\\macros' folder");
        mainPanel.add(scriptField, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        mainPanel.add(scrollPane1, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        logsArea = new JTextArea();
        logsArea.setEditable(false);
        logsArea.setEnabled(true);
        logsArea.setLineWrap(true);
        logsArea.setOpaque(true);
        scrollPane1.setViewportView(logsArea);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(5, 0, 5, 0), -1, -1));
        mainPanel.add(panel1, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Log");
        panel1.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
